apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: default-pod-viewer
  namespace: user-ood-user
rules:
  - apiGroups: [""]
    resources: ["pods","services","secrets","configmaps"]
    verbs: ["patch","get", "list", "watch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: default-pod-viewer-binding
  namespace: user-ood-user
subjects:
  - kind: ServiceAccount
    name: default
    namespace: user-ood-user
roleRef:
  kind: Role
  name: default-pod-viewer
  apiGroup: rbac.authorization.k8s.io
